### ISSUE TITLE
might be silly

### ISSUE THREAD

**Issue by 0dilon** [buzzm/ipsum#3]
hello,
I am a starter in python.
I have been trying the examples but I get the error messages : "error generating data from file "hello.jsch": Invalid format string"
to get the hello.jsch i simply copy/paste the content of the file into notepad++ and save it as hello.jsch.
Is there something special to pay attention to?
many thanks,

**Comment by buzzm** [comment]
I just ran 
Buzzs-MacBook-Pro:ipsum buzz$ python pygenipsum.py hello.jsch
{"productDate": {"$date": 134678554610}, "productName": "outlets", "productDesc": "sugars table technologies traders cooler definitions timescales every Business-to-business While", "productID": "f8a8d179-28db-44d5-84ab-db011b1e0934"}

So it should be OK.   Try downloading hello.jsch instead of copy and paste; perhaps something got picked up in the copy...?

**Comment by 0dilon** [comment]
Hello,
Many thanks for your quick answer. 
It didn't work neither on windows 7 but then I tried on Ubuntu and it worked!
Many thanks again
Odilon
